type: object
props:
    icon:
        type: image
        desc: The icon file which will be exported with the pack.
        gap: true
    name:
        type: string
        desc: The name of your pack, visible in the top left.
        hooks: [name]
    id:
        type: string
        desc: The pack's default namespace.
        default: my_pack
        nonempty: true
        allow: '*a-z0-9_'
    pack_format:
        desc: |
            A version number used to group versions with compatable assets.
            4: 1.13 - 1.14.4
            5: 1.15 - 1.16.1
            6: 1.16.2 - 1.16.5
            7: 1.17
            8: 1.18.0 - 1.18.1
            9: 1.18.2
            10: 1.19.0 - 1.19.3
            12: 1.19.4
            15: 1.20.0 - 1.20.1
            18: 1.20.2
        href: https://minecraft.wiki/w/Pack_format
        type: integer
        min: 1
        max: 18
        hooks: [refresh]
        gap: true
    version:
        type: string
        desc: The version number of your pack.
        default: "1.0.0"
    authors:
        type: list
        desc: A list of people who made this pack, one name per line.
        vals:
            type: string
    description:
        type: string
        desc: A short description of what your pack does, about one sentence long.
        ext: true
        gap: true
    license:
        type: string
        desc: |
            The license your pack falls under. If left blank, defaults to "Unknown", which typically means "All Rights Reserved".
            I recommend setting this to CC BY 4.0, which means anyone can use your pack for any purpose and make changes as they desire, as long as they give you credit.
    license_text:
        type: string
        ext: true
        desc: |
            If you want to include a LICENSE file inside your mod, datapack, and resource pack, you can put it's content in this box.
            Leaving this blank will not include a LICENSE file in the pack.
