links:
    pack_format:
        desc: |
            A version number used to group versions with compatable assets.
            4: 1.13 - 1.14.4
            5: 1.15 - 1.16.1
            6: 1.16.2 - 1.16.5
            7: 1.17
            8: 1.18.0 - 1.18.1
            9: 1.18.2
            10: 1.19.0 - 1.19.3
            12: 1.19.4
            15: 1.20.0 - 1.20.1
            18: 1.20.2
            26: 1.20.3 - 1.20.4
        href: https://minecraft.wiki/w/Pack_format
        type: integer
        min: 4
        hooks: [refresh]
    
    pack_formats:
        desc: Optional. A range of "Pack Format"s this pack supports. If specified, "pack_format" is still required and must be in this range. For an array, specify exactly two numbers for minimum and maximum versions (inclusive), no more, no less.
        unspec: none
        or:
          - title: range
            type: object
            props:
                min_inclusive:
                    link: pack_format
                max_inclusive:
                    link: pack_format
          - title: number_range
            desc: Specify exactly two numbers for minimum and maximum versions (inclusive), no more, no less.
            type: list
            vals:
                link: pack_format
          - title: single
            link: pack_format

type: object
props:
    icon:
        type: image
        desc: The icon file which will be exported with the pack.
        gap: true
    name:
        type: string
        desc: The name of your pack, visible in the top left.
        hooks: [name]
    id:
        type: string
        desc: The pack's default namespace.
        default: my_pack
        nonempty: true
        allow: '*a-z0-9_'
    pack_format:
        link: pack_format
    supported_formats:
        link: pack_formats
        gap: true
    version:
        type: string
        desc: The version number of your pack.
        default: "1.0.0"
    authors:
        type: list
        desc: A list of people who made this pack, one name per line.
        vals:
            type: string
    description:
        type: string
        desc: A short description of what your pack does, about one sentence long.
        ext: true
        gap: true
    license:
        type: string
        desc: |
            The license your pack falls under. If left blank, defaults to "Unknown", which typically means "All Rights Reserved".
            I recommend setting this to CC BY 4.0, which means anyone can use your pack for any purpose and make changes as they desire, as long as they give you credit.
    license_text:
        type: string
        desc: |
            If you want to include a LICENSE file inside your mod, datapack, and resource pack, you can put it's content in this box.
            Leaving this blank will not include a LICENSE file in the pack.
        ext: true
        gap: true
    filter:
        type: object
        desc: |
            Section for filtering out files from data packs applied below this one.
            Any file that matches one of the patterns inside block will be treated as if it was not present in the pack at all.
            NOTE: THIS FIELD IS IGNORED IN FABRIC MOD EXPORTS
        props:
            block:
                type: list
                vals:
                    type: object
                    props:
                        namespace:
                            type: string
                        path:
                            type: string
    overlays:
        type: object
        desc: |
            List of overlays. The order is important, as the first in the list will be applied first.
            Overlays are sub-packs applied over the "normal" contents of a pack.
            Their directories have their own assets and data directories, and are placed in the pack's root directory.
            NOTE: THIS FIELD IS IGNORED IN FABRIC MOD EXPORTS
        props:
            entries:
                desc: |
                    List of overlays. The order is important, as the first in the list will be applied first.
                    Overlays are sub-packs applied over the "normal" contents of a pack.
                    Their directories have their own assets and data directories, and are placed in the pack's root directory.
                    NOTE: THIS FIELD IS IGNORED IN FABRIC MOD EXPORTS
                type: list
                vals:
                    type: object
                    props:
                        formats:
                            desc: A range of pack formats when this overlay should be active
                            link: pack_formats
                        directory:
                            desc: Overlay directory.
                            type: string
                            allow: a-z0-9_-
